### PR TITLE
Fixed CHOMP configurations and launch file for porting to moveit melodic-devel

### PR DESCRIPTION
**Pull request by ghost**
We have tried your melodic-devel branch for motion planning using CHOMP of  simulation and real robot. But that was failed.

We refered from melodic-devel of ros-planning/panda_moveit_config, the launch and configurations have changed as follows:

- added parameters named 'request_adapters' in chomp_planning_pipeline.launch
- added 3 new CHOMP parameters in chomp_planning.yaml file

Then, our challenge was succeeded.

### CODE REVIEW

**Review by cjds — APPROVED** [review]
LGTM Based on reading

https://github.com/ros-planning/panda_moveit_config/blob/4e3fd7e3340a4b64304e49e8f3f3c8ccfa547e4a/launch/chomp_planning_pipeline.launch.xml#L3

**Comment by cjds** [comment]
@moriarty if you approve I'll merge

**Review by moriarty — APPROVED** [review]
SRTM

**Comment by moriarty** [comment]
Thanks @yhijioka !

**Pull request merged**
