### PR TITLE
use collision object mesh in fetch_teleop to avoid collision

### PR DESCRIPTION
**Pull request by knorth55**
related to #129 
I change to use mesh models to avoid collision between robot, keepout and ground.
we tested on indigo robot.
fetch_tuck_arm_moveit_real_robot
fetch_tuck_arm_moveit

### CODE REVIEW

**Comment by knorth55** [comment]
I found out that below link is considered as collision with ground when Fetch's torso is up high.
I will change the collision object shape to avoid this invalid collision.

**Comment by knorth55** [comment]
I updated to use mesh collision model for tuck arm script.
ground:
ground

keepout:
keepout

**Comment by knorth55** [comment]
@moriarty I'm so sorry that I made a mistake in #129 , (there was no hole in ground object).
Therefore, Fetch could not go back to reset pose when torso is up.
I fixed the problem with this PR by adding hole in ground collision object.
Could you review and merge this PR?

**Comment by knorth55** [comment]
kindly ping.
can anyone take a look and give me some review for this PR?

**Review by erelson — APPROVED** [review]

**Comment by erelson** [comment]
Sorry for the long delay here; A quick look suggests this is all good. Thank you!

**Pull request merged**
