### PR TITLE
Also require primary deadman for arm teleop

### PR DESCRIPTION
**Pull request by erelson**
Not tested yet.

Will also likely backport to indigo-devel too.

### CODE REVIEW

**Comment by erelson** [comment]
@moriarty Did you want this same logic with the head teleop?

**Comment by erelson** [comment]
Tested and verified this works with Fetch3!  Ready for review @moriarty 

Offline we discussed the head teleop, and agreed it was not a safety concern like the arm is.

I cherry picked my change onto the branch that was checked out (but made a new branch off that, namely: https://github.com/erelson/fetch_ros/tree/tf2-nav-melodic-devel_with-safer-teleop).  The robot is still set up in this manner.

**Review by moriarty — APPROVED** [review]
I was surprised the arm was safer today :+1:

**Comment by moriarty** [comment]
@erelson That's strange... this was an open PR, so I preformed a squash-and-merge and just adjusted your commit message... and I now see the two original commits were already in melodic-devel?

**Comment by moriarty** [comment]
#61 was merged into : 0.7.14 0.7.13 0.7.12 0.7.11 

Should this be back-ported to indigo?

**Comment by erelson** [comment]
I have no idea what happened there. My local melodic-devel didn't have the commits so I'm pretty sure I didn't force push them 😬 . Making backport.

**Comment by erelson** [comment]
I believe of the above releases, only 0.7.14 is one we released, but I didn't check.

**Pull request merged**
