### PR TITLE
Changing the max height for clearing to infinity so that upward-angle…

### PR DESCRIPTION
**Pull request by aaronhoy**
…d rays can still clear the costmap

### CODE REVIEW

**Comment by aaronhoy** [comment]
!set-reviewer @griswaldbrooks

**Comment by griswaldbrooks** [comment]
It seems like fetch_ros doesn't have the script to label things running. That's something @alexhenning should take a look at.

**Comment by griswaldbrooks** [comment]
Seems sensible. LGTM

**Comment by mikeferguson** [comment]
While doing this, we should also parameterize these min/max heights as ROS params

**Comment by aaronhoy** [comment]
Sounds good.  The ObstacleLayer class which this derives from already implements those as params so we can just do the same thing here and any existing use of those params should just work.  I'll update the branch momentarily.

**Comment by aaronhoy** [comment]
@griswaldbrooks @mikeferguson   Care to take another look?

**Comment by griswaldbrooks** [comment]
:+1:

**Pull request merged**
