### PR TITLE
New bag file with all leds visible

### PR DESCRIPTION
**Pull request by varunns**
Created a new bag file containing 101 poses. I have tested for the visibility of all the Led lights in  the front work space

### CODE REVIEW

**Comment by mikeferguson** [comment]
The file needs to be named calibration_poses.bag in order for the launch files to use it.

**Comment by varunns** [comment]
Renames calibration_poses_latest.bag to calibration_poses.bag

**Comment by mikeferguson** [comment]
please squash commits

**Comment by varunns** [comment]
I have squashed the commits, Kindly request for a check

**Pull request merged**
