### PR TITLE
[fetch_teleop][melodic] move collision objects to avoid collision for melodic

### PR DESCRIPTION
**Pull request by knorth55**
melodic version of #131 
I haven't tested on melodic robot because we dont have it.

### CODE REVIEW

**Comment by knorth55** [comment]
I changed to use stl mesh file for collision objects as #131,
 but I think `moveit_python` is disabled to add mesh on kinetic and melodic because of `pyassimp` problem.
`pyassimp` is broken in kinetic but fixed in melodic, so we can use `pyassimp` in melodic, but it is disabled in `moveit_python`.
I made PR to enable `pyassimp` in `moveit_python`. https://github.com/mikeferguson/moveit_python/pull/23

**Comment by knorth55** [comment]
Another choice is to stop using `moveit_python` and use `moveit_commander`.
With `moveit_commander`, you can add mesh in melodic, too.

**Comment by knorth55** [comment]
`moveit_python` `0.3.3` is released, so we can run this in Melodic.
However, we do not have Fetch with melodic, so we cannot test it by ourselves.

**Comment by knorth55** [comment]
Now, we updated our fetch to melodic and testing this PR.
`scene.addMesh()` in this PR does not work because of `pyassimp`.
I fixed the bug in `moveit_python`.
https://github.com/mikeferguson/moveit_python/pull/27

**Comment by mikeferguson** [comment]
moveit_python fix is merged and released.

**Review by erelson — APPROVED** [review]
I tested this in noetic on Fetch3. (finally)  Thanks for the PR! I'll be doing the noetic release soon, and then will try to do a melodic one as well.

**Comment by erelson** [comment]
For noetic, I've cherry-picked this PR's commits into https://github.com/fetchrobotics/fetch_ros/pull/153

**Pull request merged**
