### PR TITLE
add apply_planning_scene

### PR DESCRIPTION
**Pull request by knorth55**
add `move_group/ApplyPlanningSceneService`

cc. @708yamaguchi

### CODE REVIEW

**Comment by mikeferguson** [comment]
Thanks! I didn't even realize we hadn't added this yet.

**Comment by knorth55** [comment]
@mikeferguson 
BTW, Do you have schedule for next release?
We want to manage this package with `git tag`.

**Comment by mikeferguson** [comment]
Now released as part of 0.7.13

**Comment by knorth55** [comment]
Thank you so much!

**Pull request merged**
